CREATE TABLE package (
	PID INT AUTO_INCREMENT PRIMARY KEY,
	PON VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	qty INT NOT NULL,
	customer VARCHAR(200),
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);