CREATE TABLE items_pick (
	PID INT AUTO_INCREMENT PRIMARY KEY,
	PNO VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	qty INT NOT NULL,
	customer VARCHAR(200),
	updated_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE items_pack (
	PID INT AUTO_INCREMENT PRIMARY KEY,
	PNO VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	qty INT NOT NULL,
	customer VARCHAR(200),
	updated_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);